In [1]:
ROOT_PATH = 'C:/Users/khoan/OneDrive/Documents/stock_data_scraper'
import os
os.chdir(ROOT_PATH)

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import pandas as pd

In [4]:
from utils.generic_utils import SQLModule

In [ ]:
engine = SQLModule.get_engine(country = 'australia')

In [29]:
mid_cap_query = f"""
    SELECT
        company_name,
        fundamental->>'industry' AS industry,
        stock_code,
        fundamental->>'marketCap' AS market_cap,
        fundamental->>'priceToBook' AS pb_ratio,
        fundamental->>'profitMargins' AS profit_margins,
        fundamental->>'trailingEps' AS earning_per_share,
        fundamental->>'enterpriseToEbitda' AS evebitda,
        fundamental->>'trailingPegRatio' AS peg_ratio,
        fundamental->>'debtToEquity' AS de_ratio
    FROM stock_info
    WHERE
        CAST(fundamental->>'marketCap' AS FLOAT) >= 100000000
        AND
        CAST(fundamental->>'marketCap' AS FLOAT) < 4000000000
        AND
        CAST(fundamental->>'priceToBook' AS FLOAT) >= 0.1
        AND
        CAST(fundamental->>'priceToBook' AS FLOAT) < 1
        AND
        CAST(fundamental->>'debtToEquity' AS FLOAT) < 15
"""
df = pd.read_sql_query(mid_cap_query, engine)
df

,company_name,fundamental,industry,stock_code,market_cap,pb_ratio,profit_margins,earning_per_share,evebitda,peg_ratio,de_ratio
0,AIC Mines Limited,"{'address1': '130 Hay Street', 'address2': 'Su...",Other Precious Metals & Mining,A1M,184218560,0.8333333,0.04262,0.02,2.014,None,3.192
1,Bigtincan Holdings Ltd,"{'address1': '64 York Street', 'address2': 'Le...",Software—Application,BTH,160226816,0.6132075,-0.12092,-0.02,15.58,None,7.355
2,COAST ENTERTAINMENT HOLDINGS LTD,"{'address1': '83 Mount Street', 'address2': 'S...",Leisure,CEH,215867504,0.92081034,0.03007,-0.02,-105.363,None,0.413
3,Ainsworth Game Technology Ltd,"{'address1': '10 Holker Street', 'city': 'Newi...",Gambling,AGI,272803136,0.8173562,0.02082,None,5.406,None,10.112
4,Hancock & Gore Ltd,"{'address1': '107 Pitt Street', 'address2': 'L...",Asset Management,HNG,135973200,0.99667776,5.9543,0.02,-19.774,None,0.089
5,Iluka Resources Ltd,"{'address1': '240 St Georges Terrace', 'addres...",Other Industrial Metals & Mining,ILU,2154092544,0.94159496,0.22309,0.63,3.48,None,7.368
6,Invictus Energy Ltd,"{'address1': '10 Outram Street', 'address2': '...",Oil & Gas E&P,IVZ,101601488,0.77011496,None,None,-17.168,None,0.178
7,Aurelia Metals,"{'address1': '144 Edward Street', 'address2': ...",Other Industrial Metals & Mining,AMI,287565184,0.9090909,-0.0185,None,2.578,None,2.504
8,Ariadne Australia Ltd,"{'address1': 'Chifley Tower', 'address2': 'Lev...",Asset Management,ARA,104556128,0.6422569,0.16894,0.01,24.136,None,9.831
9,Australian Vanadium Ltd,"{'address1': '50 Kings Park Road', 'address2':...",Other Industrial Metals & Mining,AVL,103615920,0.75,None,None,-5.658,None,1.456
10,BCI Minerals Limited,"{'address1': '1 Altona Street', 'address2': 'L...",Steel,BCI,764707840,0.9498207,-1.76413,-0.03,-12.119,None,14.138
11,Bathurst Resources Limited,"{'address1': '1 Willeston Street', 'address2':...",Coking Coal,BRL,142950976,0.44444445,0.88881,0.18,26.091,None,0.604
12,Djerriwarrh Investments Ltd,"{'address1': 'Level 21', 'address2': '101 Coll...",Asset Management,DJW,849168704,0.97546196,0.72981,0.15,None,None,1.152
13,Delta Lithium Ltd,"{'address1': '18 Richardson Street', 'address2...",Gold,DLI,118229440,0.4881657,None,-0.02,-6.784,None,0.294
14,Carlton Investments Ltd,"{'address1': 'Level 15', 'address2': '478 Geor...",Asset Management,CIN,796819264,0.9064397,0.93249,1.47,None,None,0.019
15,EROAD Ltd,"{'address1': '260 Oteha Valley Road', 'address...",Software—Infrastructure,ERD,199324352,0.64820457,-0.0016500001,None,7.198,None,14.191
16,Core Lithium Ltd,"{'address1': '2 Mill Street', 'address2': 'Lev...",Other Industrial Metals & Mining,CXO,175727648,0.6833334,-1.09245,-0.1,-1.727,None,1.376
17,Helloworld Ltd,"{'address1': '179 Normanby Road', 'address2': ...",Travel Services,HLO,317495104,0.95776033,0.14112,0.19,4.304,None,6.76
18,Renascor Resources Ltd,"{'address1': '149 Flinders Street', 'address2'...",Other Industrial Metals & Mining,RNU,144895712,0.8636364,3162.3406,None,-19.034,None,0.107
19,Grange Resources Limited,"{'address1': '34A Alexander Street', 'city': '...",Steel,GRR,254614800,0.24608502,0.18625,0.09,-0.186,None,0.126
20,Gtn Ltd,"{'address1': '100 Miller Street', 'address2': ...",Advertising Agencies,GTN,113897504,0.53162235,0.030739998,0.03,7.436,None,5.342
21,Hot Chili Ltd,"{'address1': '768 Canning Highway', 'address2'...",Copper,HCH,101451400,0.44518274,None,-0.06,-11.046,None,0.224
22,Lark Distilling Co Ltd,"{'address1': '91-93 Macquarie Street', 'addres...",Beverages—Wineries & Distilleries,LRK,112776936,0.79970104,-0.27302,-0.06,-21.032,None,2.161
23,Jupiter Mines Ltd,"{'address1': '220 St Georges Terrace', 'addres...",Other Industrial Metals & Mining,JMS,274545600,0.50541514,4.81716,0.02,189.816,None,0.073
24,Mount Gibson Iron Ltd,"{'address1': '2 Kings Park Road', 'address2': ...",Steel,MGX,361472992,0.6666667,0.00963,0.01,-0.426,None,2.17
25,Mayne Pharma Group Ltd,"{'address1': '1538 Main North Road', 'city': '...",Drug Manufacturers—General,MYX,379417888,0.83542037,-0.44859,-2.12,14.654,None,8.547
26,Ssr Mining Inc,"{'address1': '6900 East Layton Avenue', 'addre...",Gold,SSR,2234164736,0.719734,-0.44129002,-3.81,-96.529,None,8.664
27,New Zealand King Salmon Co Ltd,"{'address1': '17 Bullen Street', 'address2': '...",Farm Products,NZK,110327312,0.5694444,0.120790005,0.04,2.626,None,4.918
28,Piedmont Lithium Ltd,"{'address1': '42 E Catawba Street', 'city': 'B...",Other Industrial Metals & Mining,PLL,294551136,0.9183674,-1.68196,-0.07,0.809,None,8.779
29,Patriot Battery Metals Inc.,"{'address1': '838 West Hastings Street', 'addr...",Other Industrial Metals & Mining,PMT,587594368,0.27703604,None,None,2.819,None,0.218
30,Zimplats Holdings Ltd,"{'address1': 'Elizabeth House', 'address2': '1...",Other Precious Metals & Mining,ZIM,1362697088,0.76196206,0.010720001,0.13,6.717,None,3.511
31,St Barbara Ltd,"{'address1': '58 Mounts Bay Road', 'address2':...",Gold,SBM,216570016,0.4683841,-0.24112,-0.07,-2.068,None,2.156
32,Sky Network Television Ltd.,"{'address1': '10 Panorama Road', 'address2': '...",Entertainment,SKT,341434016,0.76284224,0.06386,0.32,2.934,None,5.505
33,Sayona Mining Ltd,"{'address1': '10 Eagle Street', 'address2': 'L...",Other Industrial Metals & Mining,SYA,300125824,0.40000004,-0.50479,-0.01,-4.344,None,3.849
34,Terracom Ltd,"{'address1': 'Blair Athol Mine Access Road', '...",Thermal Coal,TER,136164224,0.8095238,0.10014,0.03,3.134,None,2.488
35,United Overseas Australia Ltd,"{'address1': 'Vertical Corporate Tower B', 'ad...",Real Estate—Development,UOS,916899520,0.53037614,0.60593,0.05,11.4,None,9.681

In [40]:
mid_cap_query = f"""
    SELECT
        company_name,
        fundamental->>'industry' AS industry,
        stock_code,
        fundamental->>'marketCap' AS market_cap,
        fundamental->>'priceToBook' AS pb_ratio,
        fundamental->>'profitMargins' AS profit_margins,
        fundamental->>'trailingEps' AS earning_per_share,
        fundamental->>'enterpriseToEbitda' AS evebitda,
        fundamental->>'trailingPegRatio' AS peg_ratio,
        fundamental->>'debtToEquity' AS de_ratio
    FROM stock_info
    WHERE
        CAST(fundamental->>'marketCap' AS FLOAT) >= 2000000000
        AND
        CAST(fundamental->>'marketCap' AS FLOAT) <= 11000000000
        AND
        fundamental->>'industry' = 'Software—Application'
"""
df = pd.read_sql_query(mid_cap_query, engine)
df

,company_name,fundamental,industry,stock_code,market_cap,pb_ratio,profit_margins,earning_per_share,evebitda,peg_ratio,de_ratio
0,Netwealth Group Ltd,"{'address1': '180 Flinders Street', 'address2'...",Software—Application,NWL,7064322560,48.75,0.32661998,0.34,53.301,None,10.32
1,Technology One Ltd,"{'address1': 'TechnologyOne HQ', 'address2': '...",Software—Application,TNE,10056775680,31.475409,0.23358999,0.36,61.61,None,8.385
2,Life360 Inc,"{'address1': '1900 South Norfolk Street', 'add...",Software—Application,360,4986240000,14.673698,-0.04724,-0.12,-318.554,None,0.238
3,Nuix Ltd,"{'address1': '1 Market Street', 'address2': 'L...",Software—Application,NXL,2037315200,6.9525957,0.022780001,0.02,31.599,None,3.409
4,PEXA Group Ltd,"{'address1': 'Tower Four Collins Square', 'add...",Software—Application,PXA,2338689024,1.90428,-0.05297,-0.1,58.95,None,30.566