In [12]:
ROOT_PATH = 'C:/Users/khoan/OneDrive/Documents/stock_data_scraper'
import os
os.chdir(ROOT_PATH)

In [13]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [14]:
from utils.generic_utils import SQLModule
import pandas as pd
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [15]:
engine = SQLModule.get_engine(country = 'australia')

In [16]:
# Collect from 'company_section.ipynb'
SECTOR = 'Consumer Defensive'

In [17]:
# Get distribution of metrics of company within the industry
query = f"""
    SELECT
        company_name,
        stock_code,
        fundamental->>'industry' AS industry,
        fundamental->>'marketCap' AS market_cap,
        fundamental->>'priceToBook' AS pb_ratio,
        fundamental->>'profitMargins' AS profit_margins,
        fundamental->>'trailingEps' AS earning_per_share,
        fundamental->>'enterpriseToEbitda' AS evebitda,
        fundamental->>'trailingPegRatio' AS peg_ratio,
        fundamental->>'debtToEquity' AS de_ratio
    FROM stock_info
    WHERE
        fundamental->>'sector' = '{SECTOR}'
"""
df = pd.read_sql_query(query, engine)
df

,company_name,stock_code,industry,market_cap,pb_ratio,profit_margins,earning_per_share,evebitda,peg_ratio,de_ratio
0,A2 Milk Company Ltd,A2M,Packaged Foods,4257231872,3.3561645,0.100150004,0.21,14.57,None,5.269
1,Australian Agricultural Company Ltd,AAC,Farm Products,849901440,0.5601907,-0.28149,0.06,-6.208,None,31.545
2,Australian Dairy Farms Group,AHF,Packaged Foods,44599320,1.4285715,-1.17458,-0.01,-5.753,None,8.428
3,Academies Australasia Group,AKG,Education & Training Services,12598330,0.7142857,-0.21089001,-0.07,-21.441,None,261.386
4,Anagenics Ltd,AN1,Household & Personal Products,3690560,1.3333334,-0.69361,-0.02,-0.878,None,28.512
...,...,...,...,...,...,...,...,...,...,...
76,Wellnex Life Ltd,WNX,Packaged Foods,28872844,3.8723404,-0.81123,-0.87,-4.873,None,176.023
77,Wide Open Agriculture Ltd,WOA,Packaged Foods,2668435,0.15624999,None,-0.06,-0.195,None,25.694
78,The Reject Shop Ltd,TRS,Discount Stores,110008160,0.6472137,0.0055299997,0.12,11.313,None,138.884
79,Top Shelf International Holdings,TSI,Beverages - Brewers,13004280,0.32,-1.12057,-0.1,-2.58,None,74.724
80,Wingara AG Ltd,WNR,Farm Products,1053258,0.54545456,-1.0527999,-0.01,0.234,None,31.769

In [18]:
# Distribution of market cap
fig = go.Figure()
fig.add_trace(
    go.Histogram(x = df['market_cap'].apply(lambda x : int(x)))
)
fig.update_yaxes(showgrid = True, gridcolor = 'gray', title = 'Number of company')
fig.update_xaxes(title = f'Market capital of company in sector "{SECTOR}"')
fig.update_layout(
    width = 1000,
    height = 500,
    plot_bgcolor = 'white',
    paper_bgcolor = 'white',
    font = dict(family = 'Lato', size = 20)
)
fig.show()

In [19]:
# Distribution of market cap
fig = go.Figure()
fig.add_trace(
    go.Histogram(x = df['pb_ratio'].apply(lambda x : float(x) if not pd.isna(x) else None))
)
fig.update_yaxes(showgrid = True, gridcolor = 'gray', title = 'Number of company')
fig.update_xaxes(title = f'P/B ratio of company in sector "{SECTOR}"')
fig.update_layout(
    width = 1000,
    height = 500,
    plot_bgcolor = 'white',
    paper_bgcolor = 'white',
    font = dict(family = 'Lato', size = 20)
)
fig.show()

In [20]:
# Distribution of market cap
fig = go.Figure()
fig.add_trace(
    go.Histogram(x = df['profit_margins'].apply(lambda x : float(x) if not pd.isna(x) else None))
)
fig.update_yaxes(showgrid = True, gridcolor = 'gray', title = 'Number of company')
fig.update_xaxes(title = f'Profit margin of company in sector "{SECTOR}"')
fig.update_layout(
    width = 1000,
    height = 500,
    plot_bgcolor = 'white',
    paper_bgcolor = 'white',
    font = dict(family = 'Lato', size = 20)
)
fig.show()

In [21]:
# Distribution of market cap
fig = go.Figure()
fig.add_trace(
    go.Histogram(x = df['earning_per_share'].apply(lambda x : float(x) if not pd.isna(x) else None))
)
fig.update_yaxes(showgrid = True, gridcolor = 'gray', title = 'Number of company')
fig.update_xaxes(title = f'EPS of company in sector "{SECTOR}"')
fig.update_layout(
    width = 1000,
    height = 500,
    plot_bgcolor = 'white',
    paper_bgcolor = 'white',
    font = dict(family = 'Lato', size = 20)
)
fig.show()

In [22]:
# Distribution of market cap
fig = go.Figure()
fig.add_trace(
    go.Histogram(x = df['evebitda'].apply(lambda x : float(x) if not pd.isna(x) else None))
)
fig.update_yaxes(showgrid = True, gridcolor = 'gray', title = 'Number of company')
fig.update_xaxes(title = f'EV/EBITDA of company in sector "{SECTOR}"')
fig.update_layout(
    width = 1000,
    height = 500,
    plot_bgcolor = 'white',
    paper_bgcolor = 'white',
    font = dict(family = 'Lato', size = 20)
)
fig.show()

In [23]:
# Distribution of market cap
fig = go.Figure()
fig.add_trace(
    go.Histogram(x = df['peg_ratio'].apply(lambda x : float(x) if not pd.isna(x) else None))
)
fig.update_yaxes(showgrid = True, gridcolor = 'gray', title = 'Number of company')
fig.update_xaxes(title = f'PEG ratio of company in sector "{SECTOR}"')
fig.update_layout(
    width = 1000,
    height = 500,
    plot_bgcolor = 'white',
    paper_bgcolor = 'white',
    font = dict(family = 'Lato', size = 20)
)
fig.show()

In [24]:
# Distribution of market cap
fig = go.Figure()
fig.add_trace(
    go.Histogram(x = df['de_ratio'].apply(lambda x : float(x) if not pd.isna(x) else None))
)
fig.update_yaxes(showgrid = True, gridcolor = 'gray', title = 'Number of company')
fig.update_xaxes(title = f'DE ratio of company in sector "{SECTOR}"')
fig.update_layout(
    width = 1000,
    height = 500,
    plot_bgcolor = 'white',
    paper_bgcolor = 'white',
    font = dict(family = 'Lato', size = 20)
)
fig.show()

In [ ]:
# Screen companies by metrics
query = f"""
    SELECT
        company_name,
        stock_code,
        fundamental->>'industry' AS industry,
        
        fundamental->>'marketCap' AS market_cap,
        fundamental->>'priceToBook' AS pb_ratio,
        fundamental->>'profitMargins' AS profit_margins,
        fundamental->>'trailingEps' AS earning_per_share,
        fundamental->>'enterpriseToEbitda' AS evebitda,
        fundamental->>'trailingPegRatio' AS peg_ratio,
        fundamental->>'debtToEquity' AS de_ratio
    FROM stock_info
    WHERE
        fundamental->>'sector' = '{SECTOR}'
        AND
        CAST(fundamental->>'trailingEps' AS FLOAT) >= 200
        
"""
screen = pd.read_sql_query(query, engine).set_index('stock_code')
screen

,company_name,industry,market_cap,pb_ratio,profit_margins,earning_per_share,evebitda,peg_ratio,de_ratio
stock_code,,,,,,,,,
NDO,Nido Petroleum Ltd,Education & Training Services,171052496,1.5,-0.08534,329.76,38.844,None,147.166

:

In [26]:
the_company = screen.loc['TNE']
the_company

KeyError: 'TNE'

In [ ]:
# Rerun the histogram, but add the company in it
fig = make_subplots(rows = 4, cols = 2)
metrics = ['market_cap', 'pb_ratio', 'profit_margins', 'earning_per_share', 'evebitda', 'peg_ratio', 'de_ratio']

for i,metric in enumerate(metrics):
    fig.add_trace(
        go.Histogram(
            x = df[metric].apply(lambda x : float(x) if not pd.isna(x) else None), 
            marker = dict(color = 'blue'),
            showlegend = False
        ),
        row = (i // 2) + 1, col = (i % 2) + 1
    )
    fig.update_xaxes(title = metric, row = (i // 2) + 1, col = (i % 2) + 1)
fig.update_yaxes(showgrid = True, gridcolor = 'gray', title = 'Number of company')

fig.update_layout(
    width = 1000,
    height = 1000,
    plot_bgcolor = 'white',
    paper_bgcolor = 'white',
    font = dict(family = 'Lato', size = 18)
)
fig_full = fig.full_figure_for_development()
for i,metric in enumerate(metrics):
    y_range = fig_full['layout'][f'yaxis{i + 1 if i > 0 else ""}']['range']
    if the_company[metric] is not None:
        fig.add_shape(
            type="line",
            x0 = the_company[metric], x1 = the_company[metric],  # X-position for the vertical line
            y0 = 0, y1 = y_range[1],      # Scaled Y-position (relative to subplot)
            line=dict(color="red", width=2),
            row = (i // 2) + 1, col = (i % 2) + 1
        )
fig.show()

c:\Users\khoan\miniconda3\envs\stock\lib\site-packages\plotly\io\_kaleido.py:338: UserWarning:

full_figure_for_development is not recommended or necessary for production use in most circumstances.
To suppress this warning, set warn=False