In [1]:
ROOT_PATH = 'C:/Users/khoan/OneDrive/Documents/stock_data_scraper'
import os
os.chdir(ROOT_PATH)

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
from utils.generic_utils import SQLModule
import pandas as pd

In [4]:
pd.set_option('display.max_rows', None)

# Australia

In [5]:
engine = SQLModule.get_engine(country = 'australia')
query = f"""
    SELECT
        fundamental->>'sector' AS sector,
        fundamental->>'industry' AS industry
    FROM stock_info
"""
df = pd.read_sql_query(query, engine)
df[['sector', 'industry']].drop_duplicates().sort_values(by = 'sector')

                      sector                                  industry
534          Basic Materials                               Coking Coal
267          Basic Materials                  Lumber & Wood Production
45           Basic Materials                                      Gold
118          Basic Materials                                 Chemicals
229          Basic Materials                                     Steel
196          Basic Materials                       Agricultural Inputs
9            Basic Materials                                  Aluminum
128          Basic Materials                                    Copper
4            Basic Materials            Other Precious Metals & Mining
3            Basic Materials          Other Industrial Metals & Mining
2286         Basic Materials                                    Silver
7            Basic Materials                        Building Materials
56           Basic Materials                       Specialty Chemicals
36    Communication Services                             Entertainment
1360  Communication Services            Electronic Gaming & Multimedia
308   Communication Services                      Advertising Agencies
622   Communication Services                                Publishing
109   Communication Services                          Telecom Services
10    Communication Services            Internet Content & Information
5     Communication Services                              Broadcasting
1217       Consumer Cyclical                     Apparel Manufacturing
201        Consumer Cyclical                                   Lodging
969        Consumer Cyclical                         Resorts & Casinos
80         Consumer Cyclical                           Internet Retail
1188       Consumer Cyclical                     Textile Manufacturing
1275       Consumer Cyclical                     Recreational Vehicles
378        Consumer Cyclical                         Personal Services
2363       Consumer Cyclical                   Home Improvement Retail
211        Consumer Cyclical        Furnishings, Fixtures & Appliances
29         Consumer Cyclical                                   Leisure
310        Consumer Cyclical                           Travel Services
24         Consumer Cyclical                  Auto & Truck Dealerships
1616       Consumer Cyclical                    Footwear & Accessories
21         Consumer Cyclical                                Auto Parts
19         Consumer Cyclical                    Packaging & Containers
327        Consumer Cyclical                            Apparel Retail
433        Consumer Cyclical                         Department Stores
2123       Consumer Cyclical                  Residential Construction
135        Consumer Cyclical                               Restaurants
636        Consumer Cyclical                              Luxury Goods
39         Consumer Cyclical                                  Gambling
30         Consumer Cyclical                          Specialty Retail
869       Consumer Defensive                   Beverages—Non-Alcoholic
147       Consumer Defensive         Beverages—Wineries & Distilleries
235       Consumer Defensive                       Beverages - Brewers
243       Consumer Defensive                            Grocery Stores
1198      Consumer Defensive                         Beverages—Brewers
146       Consumer Defensive             Education & Training Services
37        Consumer Defensive             Household & Personal Products
2262      Consumer Defensive                           Discount Stores
8         Consumer Defensive                             Farm Products
6         Consumer Defensive                            Packaged Foods
421       Consumer Defensive                         Food Distribution
1132      Consumer Defensive                             Confectioners
171                   Energy                                   Uranium
545                   Energy            Oil & Gas Refining & Marketing
375                   Energy                              Thermal Coal
2016                  Energy            Oil & Gas Equipment & Services
14                    Energy                             Oil & Gas E&P
272                Financial                          Asset Management
839       Financial Services                            Insurance—Life
28        Financial Services                          Banks - Regional
1345      Financial Services                           Shell Companies
40        Financial Services                          Asset Management
281       Financial Services                   Financial Conglomerates
41        Financial Services                            Banks—Regional
47        Financial Services                           Capital Markets
1314      Financial Services                       Insurance—Specialty
84        Financial Services                          Mortgage Finance
122       Financial Services                         Banks—Diversified
1159      Financial Services             Insurance—Property & Casualty
159       Financial Services                         Insurance Brokers
626       Financial Services          Financial Data & Stock Exchanges
190       Financial Services                           Credit Services
142               Healthcare    Drug Manufacturers—Specialty & Generic
262               Healthcare  Drug Manufacturers - Specialty & Generic
2                 Healthcare                             Biotechnology
1110              Healthcare                   Medical Care Facilities
948               Healthcare                Drug Manufacturers—General
77                Healthcare               Health Information Services
85                Healthcare                           Medical Devices
117               Healthcare            Medical Instruments & Supplies
255               Healthcare                    Diagnostics & Research
829               Healthcare                      Medical Distribution
929              Industrials                   Industrial Distribution
527              Industrials                   Airports & Air Services
857              Industrials                          Waste Management
647              Industrials            Security & Protection Services
553              Industrials                 Infrastructure Operations
577              Industrials       Farm & Heavy Construction Machinery
533              Industrials                                  Airlines
591              Industrials                 Rental & Leasing Services
0                Industrials               Specialty Business Services
145              Industrials            Specialty Industrial Machinery
254              Industrials            Staffing & Employment Services
256              Industrials                           Marine Shipping
105              Industrials            Integrated Freight & Logistics
274              Industrials                       Aerospace & Defense
127              Industrials              Electrical Equipment & Parts
299              Industrials                       Consulting Services
143              Industrials            Pollution & Treatment Controls
319              Industrials                             Conglomerates
33               Industrials                                 Railroads
332              Industrials                         Metal Fabrication
12               Industrials                Engineering & Construction
340              Industrials                                  Trucking
69               Industrials             Building Products & Equipment
54               Real Estate                          REIT—Diversified
94               Real Estate                   Real Estate—Diversified
124              Real Estate                      Real Estate Services
1095             Real Estate                REIT—Healthcare Facilities
1193             Real Estate                          REIT—Residential
217              Real Estate                               REIT—Office
278              Real Estate                        REIT - Diversified
179              Real Estate                            REIT—Specialty
180              Real Estate                               REIT—Retail
187              Real Estate                   Real Estate—Development
617              Real Estate                           REIT—Industrial
11                Technology                   Software—Infrastructure
432               Technology                   Communication Equipment
13                Technology                    Software - Application
27                Technology                      Software—Application
447               Technology                            Semiconductors
481               Technology                     Electronic Components
318               Technology       Semiconductor Equipment & Materials
158               Technology                      Consumer Electronics
562               Technology       Electronics & Computer Distribution
266               Technology        Scientific & Technical Instruments
977               Technology                         Computer Hardware
152               Technology           Information Technology Services
178               Technology                                     Solar
64                 Utilities                       Utilities—Renewable
52                 Utilities     Utilities—Independent Power Producers
108                Utilities                 Utilities—Regulated Water
22                 Utilities                   Utilities—Regulated Gas
137                Utilities                     Utilities - Renewable
360                Utilities                     Utilities—Diversified
352                Utilities              Utilities—Regulated Electric
1                       None                                      None

# Vietnam

In [6]:
engine = SQLModule.get_engine(country = 'vietnam')
query = f"""
    SELECT
        fundamental->>'sector' AS sector,
        fundamental->>'industry' AS industry
    FROM stock_info
"""
df = pd.read_sql_query(query, engine)
df[['sector', 'industry']].drop_duplicates().sort_values(by = 'sector')

                     sector                                industry
66          Basic Materials        Other Industrial Metals & Mining
133         Basic Materials                  Paper & Paper Products
146         Basic Materials                               Chemicals
32          Basic Materials                     Specialty Chemicals
28          Basic Materials                      Building Materials
26          Basic Materials                     Agricultural Inputs
8           Basic Materials                Lumber & Wood Production
158         Basic Materials                                   Steel
25   Communication Services                    Advertising Agencies
634  Communication Services                           Entertainment
254  Communication Services                        Telecom Services
106       Consumer Cyclical                Auto & Truck Dealerships
204       Consumer Cyclical                   Apparel Manufacturing
243       Consumer Cyclical                      Auto Manufacturers
244       Consumer Cyclical                Residential Construction
152       Consumer Cyclical                                 Leisure
328       Consumer Cyclical                  Packaging & Containers
390       Consumer Cyclical                            Luxury Goods
606       Consumer Cyclical                         Travel Services
183       Consumer Cyclical                        Specialty Retail
169       Consumer Cyclical      Furnishings, Fixtures & Appliances
120       Consumer Cyclical                                 Lodging
9         Consumer Cyclical                              Auto Parts
33        Consumer Cyclical                   Textile Manufacturing
1        Consumer Defensive                           Farm Products
51       Consumer Defensive                           Confectioners
61       Consumer Defensive                       Beverages—Brewers
490      Consumer Defensive           Education & Training Services
317      Consumer Defensive           Household & Personal Products
89       Consumer Defensive                                 Tobacco
27       Consumer Defensive                          Packaged Foods
414                  Energy                      Oil & Gas Drilling
10                   Energy                    Oil & Gas Integrated
94                   Energy          Oil & Gas Refining & Marketing
2        Financial Services                          Banks—Regional
4        Financial Services                   Insurance—Diversified
180      Financial Services                        Asset Management
170      Financial Services                 Financial Conglomerates
35       Financial Services                         Capital Markets
67       Financial Services           Insurance—Property & Casualty
600              Healthcare                           Biotechnology
532              Healthcare                 Medical Care Facilities
268              Healthcare                         Medical Devices
123              Healthcare  Drug Manufacturers—Specialty & Generic
250             Industrials                                Airlines
611             Industrials                               Railroads
43              Industrials          Integrated Freight & Logistics
521             Industrials           Business Equipment & Supplies
68              Industrials           Building Products & Equipment
3               Industrials                 Industrial Distribution
71              Industrials          Specialty Industrial Machinery
5               Industrials              Engineering & Construction
6               Industrials               Infrastructure Operations
46              Industrials                 Airports & Air Services
230             Industrials     Farm & Heavy Construction Machinery
148             Industrials            Electrical Equipment & Parts
154             Industrials                         Marine Shipping
23              Industrials                           Conglomerates
77              Industrials                        Waste Management
79              Real Estate                 Real Estate—Development
34              Real Estate                 Real Estate—Diversified
11              Real Estate                    Real Estate Services
624              Technology                    Consumer Electronics
168              Technology                    Software—Application
131              Technology     Electronics & Computer Distribution
92               Technology         Information Technology Services
265              Technology                   Electronic Components
392               Utilities   Utilities—Independent Power Producers
45                Utilities                 Utilities—Regulated Gas
74                Utilities            Utilities—Regulated Electric
198               Utilities                     Utilities—Renewable
459               Utilities                   Utilities—Diversified
12                Utilities               Utilities—Regulated Water
0                      None                                    None

In [8]:
# Get comany section info of a company
engine = SQLModule.get_engine(country = 'vietnam')
stock_codes = ['ACB']
mid_cap_query = f"""
    SELECT
        stock_code,
        company_name,
        fundamental->>'sector' AS sector,
        fundamental->>'industry' AS industry
    FROM stock_info
    WHERE
        stock_code IN {tuple(stock_codes) if len(stock_codes) > 1 else f"('{stock_codes[0]}')"}
"""
comp = pd.read_sql_query(mid_cap_query, engine)
comp

  stock_code          company_name              sector        industry
0        ACB  Asia Commercial Bank  Financial Services  Banks—Regional

# Untied States

In [7]:
engine = SQLModule.get_engine(country = 'united_states')
query = f"""
    SELECT
        fundamental->>'sector' AS sector,
        fundamental->>'industry' AS industry
    FROM stock_info
"""
df = pd.read_sql_query(query, engine)
df[['sector', 'industry']].drop_duplicates().sort_values(by = 'sector')

                       sector                                  industry
33075         Basic Materials                     Independent Oil & Gas
263           Basic Materials            Other Precious Metals & Mining
403           Basic Materials                       Specialty Chemicals
461           Basic Materials                  Lumber & Wood Production
623           Basic Materials                                    Copper
640           Basic Materials                                     Steel
813           Basic Materials                                 Chemicals
200           Basic Materials                                      Gold
1345          Basic Materials                       Agricultural Inputs
1357          Basic Materials                        Building Materials
2061          Basic Materials                               Coking Coal
1149          Basic Materials                                    Silver
38            Basic Materials          Other Industrial Metals & Mining
8             Basic Materials                                  Aluminum
4907          Basic Materials                    Paper & Paper Products
370    Communication Services                             Entertainment
265    Communication Services            Internet Content & Information
236    Communication Services                      Advertising Agencies
500    Communication Services            Electronic Gaming & Multimedia
221    Communication Services                          Telecom Services
507    Communication Services                                Publishing
2248   Communication Services                              Broadcasting
301         Consumer Cyclical                  Auto & Truck Dealerships
342         Consumer Cyclical                           Travel Services
3927        Consumer Cyclical                     Recreational Vehicles
498         Consumer Cyclical                                   Lodging
2006        Consumer Cyclical                         Personal Services
2885        Consumer Cyclical                  Residential Construction
783         Consumer Cyclical                    Footwear & Accessories
2656        Consumer Cyclical                   Home Improvement Retail
970         Consumer Cyclical                            Apparel Retail
2654        Consumer Cyclical                         Resorts & Casinos
1273        Consumer Cyclical                     Apparel Manufacturing
2314        Consumer Cyclical                              Luxury Goods
2271        Consumer Cyclical                         Department Stores
1481        Consumer Cyclical                        Auto Manufacturers
1538        Consumer Cyclical                     Textile Manufacturing
1866        Consumer Cyclical                               Restaurants
569         Consumer Cyclical                    Packaging & Containers
286         Consumer Cyclical                                Auto Parts
604         Consumer Cyclical        Furnishings, Fixtures & Appliances
135         Consumer Cyclical                          Specialty Retail
144         Consumer Cyclical                                   Leisure
210         Consumer Cyclical                                  Gambling
219         Consumer Cyclical                           Internet Retail
297        Consumer Defensive                         Beverages—Brewers
25996      Consumer Defensive                 Beverages - Non-Alcoholic
5415       Consumer Defensive                             Confectioners
4376       Consumer Defensive                           Discount Stores
68         Consumer Defensive             Education & Training Services
1978       Consumer Defensive                                   Tobacco
150        Consumer Defensive                             Farm Products
882        Consumer Defensive         Beverages—Wineries & Distilleries
722        Consumer Defensive             Household & Personal Products
593        Consumer Defensive                         Food Distribution
582        Consumer Defensive                            Grocery Stores
902        Consumer Defensive                   Beverages—Non-Alcoholic
423        Consumer Defensive                            Packaged Foods
1763                   Energy                                   Uranium
845                    Energy                              Thermal Coal
245                    Energy                             Oil & Gas E&P
742                    Energy            Oil & Gas Refining & Marketing
956                    Energy                        Oil & Gas Drilling
514                    Energy            Oil & Gas Equipment & Services
1918                   Energy                       Oil & Gas Midstream
825                    Energy                      Oil & Gas Integrated
285        Financial Services                     Insurance—Diversified
201        Financial Services                           Capital Markets
629        Financial Services                       Insurance—Specialty
147        Financial Services                            Insurance—Life
1492       Financial Services                         Insurance Brokers
26074      Financial Services                          Banks - Regional
178        Financial Services                            Banks—Regional
244        Financial Services                         Banks—Diversified
481        Financial Services                           Credit Services
13786      Financial Services                   Financial Conglomerates
6827       Financial Services                     Insurance—Reinsurance
583        Financial Services             Insurance—Property & Casualty
41         Financial Services                          Mortgage Finance
3067       Financial Services          Financial Data & Stock Exchanges
82         Financial Services                           Shell Companies
56         Financial Services                          Asset Management
339                Healthcare                           Medical Devices
248                Healthcare    Drug Manufacturers—Specialty & Generic
96                 Healthcare                             Biotechnology
943                Healthcare                  Pharmaceutical Retailers
264                Healthcare                Drug Manufacturers—General
26069              Healthcare  Drug Manufacturers - Specialty & Generic
1695               Healthcare                          Healthcare Plans
817                Healthcare            Medical Instruments & Supplies
479                Healthcare               Health Information Services
7                  Healthcare                    Diagnostics & Research
504                Healthcare                   Medical Care Facilities
471                Healthcare                      Medical Distribution
304               Industrials                Engineering & Construction
328               Industrials                             Conglomerates
3297              Industrials                 Infrastructure Operations
503               Industrials            Pollution & Treatment Controls
492               Industrials             Business Equipment & Supplies
1362              Industrials            Staffing & Employment Services
2563              Industrials                                  Trucking
79                Industrials            Specialty Industrial Machinery
2126              Industrials            Integrated Freight & Logistics
262               Industrials              Electrical Equipment & Parts
214               Industrials               Specialty Business Services
1863              Industrials                                 Railroads
605               Industrials                   Airports & Air Services
6910              Industrials                       Tools & Accessories
160               Industrials                       Aerospace & Defense
361               Industrials            Security & Protection Services
983               Industrials                 Rental & Leasing Services
170               Industrials                                  Airlines
805               Industrials                       Consulting Services
1260              Industrials                           Marine Shipping
784               Industrials                   Industrial Distribution
206               Industrials             Building Products & Equipment
1342              Industrials                          Waste Management
474               Industrials                         Metal Fabrication
1179              Industrials       Farm & Heavy Construction Machinery
749               Real Estate                   Real Estate—Development
916               Real Estate                REIT—Healthcare Facilities
374               Real Estate                             REIT—Mortgage
24                Real Estate                               REIT—Office
230               Real Estate                          REIT—Diversified
25955             Real Estate              REIT - Healthcare Facilities
3735              Real Estate                   Real Estate—Diversified
770               Real Estate                               REIT—Retail
516               Real Estate                           REIT—Industrial
1399              Real Estate                        REIT—Hotel & Motel
2072              Real Estate                            REIT—Specialty
1601              Real Estate                          REIT—Residential
203               Real Estate                      Real Estate Services
1010               Technology       Electronics & Computer Distribution
26037              Technology                    Software - Application
231                Technology        Scientific & Technical Instruments
212                Technology                      Consumer Electronics
501                Technology       Semiconductor Equipment & Materials
598                Technology                   Software—Infrastructure
11                 Technology                     Electronic Components
437                Technology                      Software—Application
542                Technology                         Computer Hardware
85                 Technology                                     Solar
634                Technology           Information Technology Services
60                 Technology                   Communication Equipment
808                Technology                            Semiconductors
1243                Utilities     Utilities—Independent Power Producers
418                 Utilities              Utilities—Regulated Electric
608                 Utilities                       Utilities—Renewable
982                 Utilities                 Utilities—Regulated Water
2310                Utilities                   Utilities—Regulated Gas
529                 Utilities                     Utilities—Diversified
0                        None                                      None